FROM node:20-alpine AS builder

WORKDIR /app

# Копируем зависимости
COPY package.json package-lock.json ./

# Копируем предустановленные node_modules
COPY node_modules ./node_modules

# Копируем исходный код
COPY . .

# Собираем
RUN npm run build

# Финальный образ
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]