FROM node:18-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Аргументы для сборки
ARG REACT_APP_BACKEND_URL
ARG REACT_APP_WS_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
ENV REACT_APP_WS_URL=${REACT_APP_WS_URL}
ENV PORT=415

EXPOSE 415

CMD ["npm", "start"]