version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ssh-runner-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=ssh_runner_db
    networks:
      - ssh-runner-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ssh-runner-backend:latest-offline  # Наш кастомный образ
    container_name: ssh-runner-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=ssh_runner_db
      - CORS_ORIGINS=*
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-cI31yQgFFdM8KF-iIoQN6GHRmWp82tKU_aUogjhyOWo=}
    networks:
      - ssh-runner-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: ssh-runner-frontend:latest-offline  # Наш кастомный образ
    container_name: ssh-runner-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ssh-runner-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  ssh-runner-network:
    driver: bridge