FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем Python пакеты
# (требует предварительной загрузки пакетов)
COPY pip-packages /tmp/pip-packages
RUN pip install --no-index --find-links=/tmp/pip-packages -r requirements.txt

# Копируем код
COPY . .

EXPOSE 8001
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001"]